name: Auto Create Release with Zipped Dist Folder

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Get the version from package.json (or another file)
      - name: Get version from package.json
        id: version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      # Step 3: Compress the dist folder into a zip file
      - name: Compress Dist Folder
        run: zip -r dist.zip ./dist

      # Step 4: Create a GitHub Release and upload the zipped dist folder
      - name: Create GitHub Release and Upload Dist Folder
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}  # Use the version from package.json
          name: Release v${{ env.VERSION }}  # Release name
          body: "Auto-generated release for version v${{ env.VERSION }}"  # Release description
          draft: false
          prerelease: false
          generate_release_notes: true  # Enable auto-generated release notes
          files: |
            dist.zip  # Upload the zipped dist folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}